version: "3"
services:
  ui:
    ports:
      - 127.0.0.1:30001:3000
    restart: always
    build: ui/
    environment:
      API_URL_BROWSER: /
      BASE_URL: http://service:8000
  service:
    ports:
      - 127.0.0.1:30002:8000
    environment:
      - HSTABLE_KEY
      - HSTABLE_DBIP=db
      - HSTABLE_DBPORT=3306
    restart: always
    build: service/
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=172.16.0.0/255.240.0.0

