package model

type Course struct {
	YxkcList []struct {
		Xh            string      `json:"xh"`
		Rwh           string      `json:"rwh"`
		Kcdm          string      `json:"kcdm"`
		Kcmc          string      `json:"kcmc"`
		KcmcEn        string      `json:"kcmc_en"`
		Kcxz          string      `json:"kcxz"`
		Kclb          string      `json:"kclb"`
		Xksj          string      `json:"xksj"`
		Xiaoqu        string      `json:"xiaoqu"`
		Xkbj          string      `json:"xkbj"`
		Sxbj          string      `json:"sxbj"`
		Xf            string      `json:"xf"`
		Xs            string      `json:"xs"`
		Sfxyjf        string      `json:"sfxyjf"`
		Sfxysh        string      `json:"sfxysh"`
		Skfs          string      `json:"skfs"`
		Xm            string      `json:"xm"`
		ID            string      `json:"id"`
		Xkfsdm        string      `json:"xkfsdm"`
		Kcxzmc        string      `json:"kcxzmc"`
		Kclbmc        string      `json:"kclbmc"`
		Kkyxmc        string      `json:"kkyxmc"`
		KkyxmcEn      string      `json:"kkyxmc_en"`
		Kkyx          string      `json:"kkyx"`
		Xiaoqumc      string      `json:"xiaoqumc"`
		XiaoqumcEn    string      `json:"xiaoqumc_en"`
		Rwlxmc        string      `json:"rwlxmc"`
		Xkfsmc        string      `json:"xkfsmc"`
		XkfsmcEn      string      `json:"xkfsmc_en"`
		Xkms          string      `json:"xkms"`
		Zrl           string      `json:"zrl"`
		Bksrl         string      `json:"bksrl"`
		Yjsrl         string      `json:"yjsrl"`
		Yxzrs         string      `json:"yxzrs"`
		Bksyxrs       string      `json:"bksyxrs"`
		Yjsyxrs       string      `json:"yjsyxrs"`
		Nansyxrs      string      `json:"nansyxrs"`
		Nvsyxrs       string      `json:"nvsyxrs"`
		Dnyxrs        string      `json:"dnyxrs"`
		Dwyxrs        string      `json:"dwyxrs"`
		Yxzrlrs       string      `json:"yxzrlrs"`
		Bksyxrlrs     string      `json:"bksyxrlrs"`
		Yjsyxrlrs     string      `json:"yjsyxrlrs"`
		Nansyxrlrs    string      `json:"nansyxrlrs"`
		Nvsyxrlrs     string      `json:"nvsyxrlrs"`
		Dnyxrlrs      string      `json:"dnyxrlrs"`
		Dwyxrlrs      string      `json:"dwyxrlrs"`
		DwrlFx        string      `json:"dwrl_fx"`
		DwrlWzy       string      `json:"dwrl_wzy"`
		DwyxrsFx      string      `json:"dwyxrs_fx"`
		DwyxrsWzy     string      `json:"dwyxrs_wzy"`
		DwyxrlrsFx    string      `json:"dwyxrlrs_fx"`
		DwyxrlrsWzy   string      `json:"dwyxrlrs_wzy"`
		Rwmc          string      `json:"rwmc"`
		Sfxyjfsh      string      `json:"sfxyjfsh"`
		Sfkt          string      `json:"sfkt"`
		Zksfkt        string      `json:"zksfkt"`
		Cqxzsfkt      string      `json:"cqxzsfkt"`
		Ktxkkssj      string      `json:"ktxkkssj"`
		Ktxkjssj      string      `json:"ktxkjssj"`
		Tksfjw        string      `json:"tksfjw"`
		Sfzktsjn      string      `json:"sfzktsjn"`
		Sfzjfsjn      string      `json:"sfzjfsjn"`
		Njmc          string      `json:"njmc"`
		Yxmc          string      `json:"yxmc"`
		YxmcEn        string      `json:"yxmc_en"`
		Zymc          string      `json:"zymc"`
		ZymcEn        string      `json:"zymc_en"`
		Rwid          string      `json:"rwid"`
		Sfxycq        string      `json:"sfxycq"`
		Xnxqmc        string      `json:"xnxqmc"`
		Kcid          string      `json:"kcid"`
		Kcxx          string      `json:"kcxx"`
		KcxxEn        string      `json:"kcxx_en"`
		Dgjsmc        string      `json:"dgjsmc"`
		Pkjgmx        string      `json:"pkjgmx"`
		PkjgmxEn      string      `json:"pkjgmx_en"`
		Tyxmmc        string      `json:"tyxmmc"`
		Rlxszd        string      `json:"rlxszd"`
	} `json:"yxkcList"`
}